In [1]:
import pandas as pd

In [2]:
house_data = pd.read_csv("HousePricePrediction.csv")

In [3]:
house_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
# encoding columns with categorical values for linear regression
columns_to_encode = ['MSSubClass', 'MSZoning','LotConfig','BldgType','Exterior1st']

In [6]:
encoders = {col: LabelEncoder() for col in columns_to_encode}

In [7]:
#duplicating to avoid losing data if some important column gets dropped
house_data2 = house_data

In [8]:
# applied fit_transform on the whole dataset first should have split to avoid data_leakage
for col in columns_to_encode:
    house_data2[col] = encoders[col].fit_transform(house_data2[col])

In [9]:
house_data2

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,5,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.0
1,1,0,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.0
2,2,5,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.0
3,3,6,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.0
4,4,5,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,13,4,1936,4,3,7,1970,1970,5,0.0,546.0,NaN
2915,2915,13,4,1894,4,4,5,1970,1970,5,0.0,546.0,NaN
2916,2916,0,3,20000,4,0,7,1960,1996,12,0.0,1224.0,NaN
2917,2917,9,3,10441,4,0,5,1992,1992,6,0.0,912.0,NaN
2918,2918,5,3,9627,4,0,5,1993,1994,6,0.0,996.0,NaN

In [10]:
house_data2["year"]=house_data2['YearRemodAdd']-house_data2['YearBuilt']

In [11]:
house_data2

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,year
0,0,5,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.0,0
1,1,0,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.0,0
2,2,5,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.0,1
3,3,6,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.0,55
4,4,5,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,13,4,1936,4,3,7,1970,1970,5,0.0,546.0,NaN,0
2915,2915,13,4,1894,4,4,5,1970,1970,5,0.0,546.0,NaN,0
2916,2916,0,3,20000,4,0,7,1960,1996,12,0.0,1224.0,NaN,36
2917,2917,9,3,10441,4,0,5,1992,1992,6,0.0,912.0,NaN,0
2918,2918,5,3,9627,4,0,5,1993,1994,6,0.0,996.0,NaN,1

In [12]:
# checking nan values, didn't work 
house_data2 = house_data2[house_data2["SalePrice"] != "NaN"]

In [13]:
house_data2

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,year
0,0,5,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.0,0
1,1,0,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.0,0
2,2,5,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.0,1
3,3,6,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.0,55
4,4,5,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,13,4,1936,4,3,7,1970,1970,5,0.0,546.0,NaN,0
2915,2915,13,4,1894,4,4,5,1970,1970,5,0.0,546.0,NaN,0
2916,2916,0,3,20000,4,0,7,1960,1996,12,0.0,1224.0,NaN,36
2917,2917,9,3,10441,4,0,5,1992,1992,6,0.0,912.0,NaN,0
2918,2918,5,3,9627,4,0,5,1993,1994,6,0.0,996.0,NaN,1

In [14]:
# counting nan values in saleprice
house_data2['SalePrice'].isna().sum()

np.int64(1459)

In [15]:
# dropping nan rows because can't use those rows to predict
house_data2 = house_data2.dropna(subset=['SalePrice'])

In [16]:
house_data2

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,year
0,0,5,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.0,0
1,1,0,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.0,0
2,2,5,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.0,1
3,3,6,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.0,55
4,4,5,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,5,3,7917,4,0,5,1999,2000,12,0.0,953.0,175000.0,1
1456,1456,0,3,13175,4,0,6,1978,1988,9,163.0,1542.0,210000.0,10
1457,1457,6,3,9042,4,0,9,1941,2006,5,0.0,1152.0,266500.0,65
1458,1458,0,3,9717,4,0,6,1950,1996,8,1029.0,1078.0,142125.0,46
1459,1459,0,3,9937,4,0,6,1965,1965,6,290.0,1256.0,147500.0,0

In [17]:
# dropping all irrelevant features (looked irrelevant)
X=house_data2.drop(columns=["YearBuilt","YearRemodAdd","Exterior1st","BsmtFinSF2","TotalBsmtSF","SalePrice"])

In [18]:
X

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,year
0,0,5,3,8450,4,0,5,0
1,1,0,3,9600,2,0,8,0
2,2,5,3,11250,4,0,5,1
3,3,6,3,9550,0,0,5,55
4,4,5,3,14260,2,0,5,0
...,...,...,...,...,...,...,...,...
1455,1455,5,3,7917,4,0,5,1
1456,1456,0,3,13175,4,0,6,10
1457,1457,6,3,9042,4,0,9,65
1458,1458,0,3,9717,4,0,6,46
1459,1459,0,3,9937,4,0,6,0

In [19]:
y = house_data2["SalePrice"]

In [20]:
y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
X_train, y_train

(        Id  MSSubClass  MSZoning  LotArea  LotConfig  BldgType  OverallCond  \
 254    254           0         3     8400          4         0            6
 1066  1066           5         3     7837          4         0            7
 638    638           1         3     8777          4         0            7
 799    799           4         3     7200          0         0            7
 380    380           4         3     5000          4         0            6
 ...    ...         ...       ...      ...        ...       ...          ...
 1095  1095           0         3     9317          4         0            5
 1130  1130           4         3     7804          4         0            3
 1294  1294           0         3     8172          4         0            7
 860    860           4         3     7642          0         0            8
 1126  1126          11         3     3684          4         4            5

       year
 254      0
 1066     1
 638     40
 799     13
 380     26
 ...    ...
 1095     0
 1130    22
 1294    35
 860     80
 1126     0

 [1168 rows x 8 columns],
 254     145000.0
 1066    178000.0
 638      85000.0
 799     175000.0
 380     127000.0
           ...
 1095    176432.0
 1130    135000.0
 1294    115000.0
 860     189950.0
 1126    174000.0
 Name: SalePrice, Length: 1168, dtype: float64)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model = LinearRegression()

In [26]:
model.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred = model.predict(X_test)

In [103]:
y_pred, y_test

(array([142070.44 , 268971.22 , 126366.695, 109482.03 , 265577.94 ,
         97476.48 , 196924.02 , 161869.36 ,  91995.85 , 202039.64 ,
        132417.12 , 167627.77 ,  98007.54 , 192313.88 , 182352.69 ,
        130728.984, 192575.03 , 131931.8  ,  95564.09 , 152591.38 ,
        115998.16 , 268721.38 , 201127.62 , 116036.51 , 162002.02 ,
        196293.34 , 155397.58 , 221393.6  , 220640.44 , 203555.88 ,
        171572.89 , 253538.61 , 194939.52 , 134387.1  , 193811.86 ,
        193437.14 , 104970.734, 183340.66 , 215734.84 , 237640.75 ,
        115058.3  , 159258.17 , 175692.25 , 313197.8  , 211955.89 ,
        113218.49 , 143471.53 , 132703.81 , 227431.14 , 226112.   ,
        136057.84 , 178364.12 , 132389.97 , 194110.3  , 150444.06 ,
        200482.2  , 216284.69 , 223750.84 , 156033.61 , 125597.74 ,
        114144.31 , 134892.16 , 232450.44 , 318772.25 , 339961.5  ,
        201349.25 , 134999.97 , 266750.44 , 235317.23 , 166569.31 ,
        145319.31 , 139188.52 , 150484.95 , 109740.24 , 264722.47 ,
        172705.22 , 251590.66 , 245617.44 , 130865.08 , 124034.54 ,
        104266.6  ,  64770.125, 221494.84 , 110459.58 , 177375.12 ,
        129089.45 , 285014.8  , 169689.42 , 160259.77 , 239107.58 ,
        129509.266, 232031.   , 120549.84 , 260952.55 , 101396.58 ,
        239147.33 , 134106.47 , 165519.45 , 161883.5  , 227247.52 ,
        131261.17 , 187663.86 , 141681.75 , 126765.19 , 257561.14 ,
         99950.37 , 139853.16 , 157753.77 , 226986.08 , 224485.56 ,
         73377.516, 149609.81 , 128131.04 , 128943.38 , 212239.92 ,
        114153.71 , 112800.79 , 135284.72 , 146513.4  , 238572.72 ,
        173873.28 , 162123.53 , 202726.67 , 138080.95 , 213737.64 ,
        178187.34 , 205714.28 , 123174.12 , 146058.08 , 229416.42 ,
        181652.48 , 280521.88 , 204569.77 , 111368.72 , 171327.88 ,
        252911.8  , 211576.44 , 146342.2  , 148720.28 , 305505.38 ,
        366981.3  , 190393.4  , 202433.69 , 108443.58 , 171309.98 ,
        149331.33 , 132825.84 , 387949.2  , 147732.03 ,  62675.33 ,
         99882.2  , 181930.52 , 188144.58 , 124706.78 ,  76594.74 ,
        161564.31 , 108953.27 , 221594.47 , 109314.75 , 162072.58 ,
        172614.25 , 149851.3  , 222406.3  , 138249.25 , 133452.67 ,
        107181.07 , 213666.36 , 220366.22 , 303903.5  , 250200.78 ,
        317219.66 , 133323.3  , 109682.46 ,  98858.445, 132298.89 ,
        162353.48 , 122395.75 , 252560.02 , 133848.95 , 155384.81 ,
        162723.84 , 240658.77 , 166268.   , 122483.51 , 231009.08 ,
        185240.48 , 200913.31 , 189235.5  , 208847.61 , 102309.16 ,
        107082.58 , 106380.64 , 138102.72 , 162155.62 , 196903.33 ,
        146503.62 , 204479.6  , 144462.64 , 167985.8  , 134282.64 ,
        305355.75 , 306788.8  , 178397.61 , 217254.62 , 156438.38 ,
        167720.31 , 219824.88 , 144019.19 , 104223.99 , 170299.33 ,
        353055.53 , 143253.42 , 163675.22 , 163372.16 , 246904.   ,
        280767.8  , 201727.89 , 155379.98 , 115445.29 , 147174.62 ,
        254656.58 , 201895.12 , 187793.25 , 100859.33 , 158737.88 ,
        162565.05 ,  96517.375, 114342.516, 198077.56 , 149683.88 ,
        150850.94 , 190596.58 , 134207.36 , 180633.02 , 225663.36 ,
        168818.33 , 149192.1  , 154109.64 , 372081.94 , 184762.31 ,
        112784.28 , 157589.34 , 191877.89 , 236743.69 , 194987.19 ,
        137206.55 , 167676.36 , 177497.14 , 192814.19 , 146479.39 ,
        207050.48 , 171239.7  , 117496.6  ,  89307.8  , 197770.55 ,
        153020.78 , 146079.78 , 106283.805, 177388.92 , 243388.36 ,
        297545.7  , 207770.72 , 152898.   , 174497.66 , 180309.73 ,
        246458.27 , 151689.9  , 192890.78 , 190333.2  , 180047.48 ,
        240202.14 , 243223.1  , 211582.58 , 105532.79 , 143574.67 ,
        151826.64 , 127462.13 , 169593.5  , 238946.53 , 147884.16 ,
        256597.69 , 104475.72 , 215931.94 , 141515.97 , 241619.95 ,
        173397.69 , 266062.25 ,  97959.69 , 236780.9  , 180445.58 ,
        133285.67 , 171603.8  ], dtype=float32),
 892     154500.0
 1105    325000.0
 413     115000.0
 522     159000.0
 1036    315500.0
           ...
 479      89471.0
 1361    260000.0
 802     189000.0
 651     108000.0
 722     124500.0
 Name: SalePrice, Length: 292, dtype: float64)

In [30]:
import numpy as np

In [31]:
print(np.isnan(y_test).sum())

0

In [32]:
print(y_test.index[:5])

Index([892, 1105, 413, 522, 1036], dtype='int64')

In [33]:
import matplotlib.pyplot as plt

In [34]:
print(y_pred.shape)
print(y_test.shape)

(292,)
(292,)

In [35]:
X

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,year
0,0,5,3,8450,4,0,5,0
1,1,0,3,9600,2,0,8,0
2,2,5,3,11250,4,0,5,1
3,3,6,3,9550,0,0,5,55
4,4,5,3,14260,2,0,5,0
...,...,...,...,...,...,...,...,...
1455,1455,5,3,7917,4,0,5,1
1456,1456,0,3,13175,4,0,6,10
1457,1457,6,3,9042,4,0,9,65
1458,1458,0,3,9717,4,0,6,46
1459,1459,0,3,9937,4,0,6,0

In [36]:
y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [37]:
from sklearn.metrics import mean_absolute_error

In [38]:
# check metrics after linear regression
mae = mean_absolute_error(y_test, y_pred)

In [39]:
mae

56070.42873739235

In [40]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

In [41]:
# check other metrics - here r2_score most important in house prediction case
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2s = r2_score(y_test, y_pred)

In [42]:
# r2_score very low, features definitely not linearly dependent
mse, rmse, r2s

(6782992070.261309, 82358.92222620029, 0.11568401564126185)

In [43]:
y_test.mean()

np.float64(178839.81164383562)

In [44]:
y_test.max(), y_test.min(), y_test.std()

(np.float64(755000.0), np.float64(35311.0), np.float64(87730.75125912335))

In [45]:
y_pred.mean()

np.float64(180802.03326865443)

In [46]:
# model 2 - random forest
from sklearn.ensemble import RandomForestRegressor
model2 = RandomForestRegressor(random_state=42)

In [47]:
model2.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [48]:
y_pred = model2.predict(X_test)

In [49]:
mae = mean_absolute_error(y_test, y_pred)

In [50]:
mae

44674.3025

In [51]:
rmse = root_mean_squared_error(y_test, y_pred)

In [52]:
rmse

67695.05148455386

In [53]:
r2 = r2_score(y_test, y_pred)

In [54]:
# r2_score still low but more than 0.117, no linear relation between features
r2

0.4025521377171072

In [55]:
# model 3 - xgboost
from xgboost import XGBRegressor
model3 = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6, random_state=42)

In [56]:
model3.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [57]:
y_pred = model3.predict(X_test)

In [58]:
r2 = r2_score(y_test, y_pred)

In [59]:
# not much but more than linear and random forest, therefore the best option
r2

0.416138167327898

In [60]:
# data transformation since at most the r2_score is 0.416 even with xgboost
# use one hot encoding
house_data2 = pd.get_dummies(
    house_data2,
    columns=['MSZoning', 'LotConfig'],
    drop_first=True
)

In [61]:
house_data2

,Id,MSSubClass,LotArea,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,year,MSZoning_1,MSZoning_2,MSZoning_3,MSZoning_4,LotConfig_1,LotConfig_2,LotConfig_3,LotConfig_4
0,0,5,8450,0,5,2003,2003,12,0.0,856.0,208500.0,0,False,False,True,False,False,False,False,True
1,1,0,9600,0,8,1976,1976,8,0.0,1262.0,181500.0,0,False,False,True,False,False,True,False,False
2,2,5,11250,0,5,2001,2002,12,0.0,920.0,223500.0,1,False,False,True,False,False,False,False,True
3,3,6,9550,0,5,1915,1970,13,0.0,756.0,140000.0,55,False,False,True,False,False,False,False,False
4,4,5,14260,0,5,2000,2000,12,0.0,1145.0,250000.0,0,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,5,7917,0,5,1999,2000,12,0.0,953.0,175000.0,1,False,False,True,False,False,False,False,True
1456,1456,0,13175,0,6,1978,1988,9,163.0,1542.0,210000.0,10,False,False,True,False,False,False,False,True
1457,1457,6,9042,0,9,1941,2006,5,0.0,1152.0,266500.0,65,False,False,True,False,False,False,False,True
1458,1458,0,9717,0,6,1950,1996,8,1029.0,1078.0,142125.0,46,False,False,True,False,False,False,False,True
1459,1459,0,9937,0,6,1965,1965,6,290.0,1256.0,147500.0,0,False,False,True,False,False,False,False,True

In [62]:
X=house_data2.drop(columns = ["SalePrice"])
y=house_data2["SalePrice"]

In [63]:
X, y

(        Id  MSSubClass  LotArea  BldgType  OverallCond  YearBuilt  \
 0        0           5     8450         0            5       2003
 1        1           0     9600         0            8       1976
 2        2           5    11250         0            5       2001
 3        3           6     9550         0            5       1915
 4        4           5    14260         0            5       2000
 ...    ...         ...      ...       ...          ...        ...
 1455  1455           5     7917         0            5       1999
 1456  1456           0    13175         0            6       1978
 1457  1457           6     9042         0            9       1941
 1458  1458           0     9717         0            6       1950
 1459  1459           0     9937         0            6       1965

       YearRemodAdd  Exterior1st  BsmtFinSF2  TotalBsmtSF  year  MSZoning_1  \
 0             2003           12         0.0        856.0     0       False
 1             1976            8         0.0       1262.0     0       False
 2             2002           12         0.0        920.0     1       False
 3             1970           13         0.0        756.0    55       False
 4             2000           12         0.0       1145.0     0       False
 ...            ...          ...         ...          ...   ...         ...
 1455          2000           12         0.0        953.0     1       False
 1456          1988            9       163.0       1542.0    10       False
 1457          2006            5         0.0       1152.0    65       False
 1458          1996            8      1029.0       1078.0    46       False
 1459          1965            6       290.0       1256.0     0       False

       MSZoning_2  MSZoning_3  MSZoning_4  LotConfig_1  LotConfig_2  \
 0          False        True       False        False        False
 1          False        True       False        False         True
 2          False        True       False        False        False
 3          False        True       False        False        False
 4          False        True       False        False         True
 ...          ...         ...         ...          ...          ...
 1455       False        True       False        False        False
 1456       False        True       False        False        False
 1457       False        True       False        False        False
 1458       False        True       False        False        False
 1459       False        True       False        False        False

       LotConfig_3  LotConfig_4
 0           False         True
 1           False        False
 2           False         True
 3           False        False
 4           False        False
 ...           ...          ...
 1455        False         True
 1456        False         True
 1457        False         True
 1458        False         True
 1459        False         True

 [1460 rows x 19 columns],
 0       208500.0
 1       181500.0
 2       223500.0
 3       140000.0
 4       250000.0
           ...
 1455    175000.0
 1456    210000.0
 1457    266500.0
 1458    142125.0
 1459    147500.0
 Name: SalePrice, Length: 1460, dtype: float64)

In [64]:
# train test split before target encoding to avoid data leakage
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:
# use target encoding since model will mistake greater value for more priority/importance which isn't the case for these features
class_price = y_train2.groupby(X_train2["MSSubClass"]).mean()

In [66]:
class_price

MSSubClass
0     185360.011521
1      95864.000000
2     181666.666667
3     106790.000000
4     141253.274336
5     238509.233333
6     171507.115385
7     198333.333333
8     169551.555556
9     150135.294118
10    135883.390244
11    203610.093750
13    138426.224490
14    110142.857143
15    129853.571429
Name: SalePrice, dtype: float64

In [67]:
class_price.shape

(15,)

In [68]:
for i in class_price:
    print(i)

185360.01152073732
95864.0
181666.66666666666
106790.0
141253.27433628318
238509.23333333334
171507.11538461538
198333.33333333334
169551.55555555556
150135.29411764705
135883.39024390245
203610.09375
138426.22448979592
110142.85714285714
129853.57142857143

In [69]:
X_train2["MSSubClass_encoded"] = X_train2["MSSubClass"].map(class_price)

In [70]:
X_test2["MSSubClass_encoded"] = X_test2["MSSubClass"].map(class_price)

In [71]:
X_train2 = X_train2.drop(columns=["MSSubClass"])
X_test2 = X_test2.drop(columns=["MSSubClass"])

In [72]:
# second column one hot encoding
ex_1 = y_train2.groupby(X_train2["Exterior1st"]).mean()

In [73]:
X_train2["Exterior1st_encoded"] = X_train2["Exterior1st"].map(ex_1)

In [74]:
X_test2["Exterior1st_encoded"] = X_test2["Exterior1st"].map(ex_1)

In [75]:
X_train2 = X_train2.drop(columns=["Exterior1st"])
X_test2 = X_test2.drop(columns=["Exterior1st"])

In [76]:
X_train2, X_test2

(        Id  LotArea  BldgType  OverallCond  YearBuilt  YearRemodAdd  \
 254    254     8400         0            6       1957          1957
 1066  1066     7837         0            7       1993          1994
 638    638     8777         0            7       1910          1950
 799    799     7200         0            7       1937          1950
 380    380     5000         0            6       1924          1950
 ...    ...      ...       ...          ...        ...           ...
 1095  1095     9317         0            5       2006          2006
 1130  1130     7804         0            3       1928          1950
 1294  1294     8172         0            7       1955          1990
 860    860     7642         0            8       1918          1998
 1126  1126     3684         4            5       2007          2007

       BsmtFinSF2  TotalBsmtSF  year  MSZoning_1  MSZoning_2  MSZoning_3  \
 254          0.0       1314.0     0       False       False        True
 1066         0.0        799.0     1       False       False        True
 638          0.0        796.0    40       False       False        True
 799          0.0        731.0    13       False       False        True
 380          0.0       1026.0    26       False       False        True
 ...          ...          ...   ...         ...         ...         ...
 1095         0.0       1314.0     0       False       False        True
 1130         0.0       1122.0    22       False       False        True
 1294         0.0        864.0    35       False       False        True
 860          0.0        912.0    80       False       False        True
 1126         0.0       1373.0     0       False       False        True

       MSZoning_4  LotConfig_1  LotConfig_2  LotConfig_3  LotConfig_4  \
 254        False        False        False        False         True
 1066       False        False        False        False         True
 638        False        False        False        False         True
 799        False        False        False        False        False
 380        False        False        False        False         True
 ...          ...          ...          ...          ...          ...
 1095       False        False        False        False         True
 1130       False        False        False        False         True
 1294       False        False        False        False         True
 860        False        False        False        False        False
 1126       False        False        False        False         True

       MSSubClass_encoded  Exterior1st_encoded
 254        185360.011521        149444.855491
 1066       238509.233333        212996.819048
 638         95864.000000        149444.855491
 799        141253.274336        150770.684211
 380        141253.274336        206627.500000
 ...                  ...                  ...
 1095       185360.011521        212996.819048
 1130       141253.274336        148931.578947
 1294       185360.011521        148931.578947
 860        141253.274336        150770.684211
 1126       203610.093750        212996.819048

 [1168 rows x 19 columns],
         Id  LotArea  BldgType  OverallCond  YearBuilt  YearRemodAdd  \
 892    892     8414         0            8       1963          2003
 1105  1105    12256         0            5       1994          1995
 413    413     8960         0            6       1927          1950
 522    522     5000         0            7       1947          1950
 1036  1036    12898         0            5       2007          2008
 ...    ...      ...       ...          ...        ...           ...
 479    479     5925         0            7       1937          2000
 1361  1361    16158         0            5       2005          2005
 802    802     8199         0            5       2005          2005
 651    651     9084         0            5       1940          1950
 722    722     8120         0            7       1970          1970

       BsmtFinSF2  TotalBsmtSF  year  MSZoning_1  MSZoning_2  MSZoning_3  \
 892          0.0       1059.0    40       False       False        True
 1105         0.0       1463.0     1       False       False        True
 413          0.0       1008.0    23       False       False       False
 522          0.0       1004.0     3       False       False       False
 1036         0.0       1620.0     1       False       False        True
 ...          ...          ...   ...         ...         ...         ...
 479          0.0        907.0    63       False       False       False
 1361         0.0       1530.0     0       False       False        True
 802          0.0        728.0     0       False       False        True
 651          0.0        755.0    10       False       False        True
 722          0.0        864.0     0       False       False        True

       MSZoning_4  LotConfig_1  LotConfig_2  LotConfig_3  LotConfig_4  \
 892        False        False        False        False         True
 1105       False        False        False        False        False
 413         True        False        False        False         True
 522         True        False        False        False        False
 1036       False        False        False        False         True
 ...          ...          ...          ...          ...          ...
 479         True        False        False        False         True
 1361       False        False        False        False         True
 802        False        False        False        False         True
 651        False        False        False        False         True
 722        False        False        False        False         True

       MSSubClass_encoded  Exterior1st_encoded
 892        185360.011521        160857.352273
 1105       238509.233333        160857.352273
 413         95864.000000        148931.578947
 522        141253.274336        238507.266667
 1036       185360.011521        212996.819048
 ...                  ...                  ...
 479         95864.000000        175465.666667
 1361       185360.011521        212996.819048
 802        238509.233333        148931.578947
 651        171507.115385        149444.855491
 722        185360.011521        149444.855491

 [292 rows x 19 columns])

In [77]:
# model 4 - xgboost
model4 = XGBRegressor(n_estimators=200, random_state=42, learning_rate=0.05, max_depth=6,)

In [78]:
# dropping the redundant columns
X_train2 = X_train2.drop(columns=["Id", "YearBuilt", "YearRemodAdd"])
X_test2 = X_test2.drop(columns=["Id", "YearBuilt", "YearRemodAdd"])

In [79]:
# drop basement square foot
X_train2 = X_train2.drop(columns=["BsmtFinSF2"])
X_test2 = X_test2.drop(columns=["BsmtFinSF2"])

In [80]:
# log transformation for total basement square foot
X_train2['TotalBsmtSF_log'] = np.log1p(X_train2['TotalBsmtSF'])
X_test2['TotalBsmtSF_log'] = np.log1p(X_test2['TotalBsmtSF'])

# Drop the old raw basement columns and the useless SF2 column
drop_cols = ['TotalBsmtSF']
X_train2 = X_train2.drop(columns=drop_cols, errors='ignore')
X_test2 = X_test2.drop(columns=drop_cols, errors='ignore')

In [81]:
# final train test data
X_train2, X_test2

(      LotArea  BldgType  OverallCond  year  MSZoning_1  MSZoning_2  \
 254      8400         0            6     0       False       False
 1066     7837         0            7     1       False       False
 638      8777         0            7    40       False       False
 799      7200         0            7    13       False       False
 380      5000         0            6    26       False       False
 ...       ...       ...          ...   ...         ...         ...
 1095     9317         0            5     0       False       False
 1130     7804         0            3    22       False       False
 1294     8172         0            7    35       False       False
 860      7642         0            8    80       False       False
 1126     3684         4            5     0       False       False

       MSZoning_3  MSZoning_4  LotConfig_1  LotConfig_2  LotConfig_3  \
 254         True       False        False        False        False
 1066        True       False        False        False        False
 638         True       False        False        False        False
 799         True       False        False        False        False
 380         True       False        False        False        False
 ...          ...         ...          ...          ...          ...
 1095        True       False        False        False        False
 1130        True       False        False        False        False
 1294        True       False        False        False        False
 860         True       False        False        False        False
 1126        True       False        False        False        False

       LotConfig_4  MSSubClass_encoded  Exterior1st_encoded  TotalBsmtSF_log
 254          True       185360.011521        149444.855491         7.181592
 1066         True       238509.233333        212996.819048         6.684612
 638          True        95864.000000        149444.855491         6.680855
 799         False       141253.274336        150770.684211         6.595781
 380          True       141253.274336        206627.500000         6.934397
 ...           ...                 ...                  ...              ...
 1095         True       185360.011521        212996.819048         7.181592
 1130         True       141253.274336        148931.578947         7.023759
 1294         True       185360.011521        148931.578947         6.762730
 860         False       141253.274336        150770.684211         6.816736
 1126         True       203610.093750        212996.819048         7.225481

 [1168 rows x 15 columns],
       LotArea  BldgType  OverallCond  year  MSZoning_1  MSZoning_2  \
 892      8414         0            8    40       False       False
 1105    12256         0            5     1       False       False
 413      8960         0            6    23       False       False
 522      5000         0            7     3       False       False
 1036    12898         0            5     1       False       False
 ...       ...       ...          ...   ...         ...         ...
 479      5925         0            7    63       False       False
 1361    16158         0            5     0       False       False
 802      8199         0            5     0       False       False
 651      9084         0            5    10       False       False
 722      8120         0            7     0       False       False

       MSZoning_3  MSZoning_4  LotConfig_1  LotConfig_2  LotConfig_3  \
 892         True       False        False        False        False
 1105        True       False        False        False        False
 413        False        True        False        False        False
 522        False        True        False        False        False
 1036        True       False        False        False        False
 ...          ...         ...          ...          ...          ...
 479        False        True        False        False        False
 1361        True       False        False        False        False
 802         True       False        False        False        False
 651         True       False        False        False        False
 722         True       False        False        False        False

       LotConfig_4  MSSubClass_encoded  Exterior1st_encoded  TotalBsmtSF_log
 892          True       185360.011521        160857.352273         6.966024
 1105        False       238509.233333        160857.352273         7.288928
 413          True        95864.000000        148931.578947         6.916715
 522         False       141253.274336        238507.266667         6.912743
 1036         True       185360.011521        212996.819048         7.390799
 ...           ...                 ...                  ...              ...
 479          True        95864.000000        175465.666667         6.811244
 1361         True       185360.011521        212996.819048         7.333676
 802          True       238509.233333        148931.578947         6.591674
 651          True       171507.115385        149444.855491         6.628041
 722          True       185360.011521        149444.855491         6.762730

 [292 rows x 15 columns])

In [82]:
y_train, y_test

(254     145000.0
 1066    178000.0
 638      85000.0
 799     175000.0
 380     127000.0
           ...
 1095    176432.0
 1130    135000.0
 1294    115000.0
 860     189950.0
 1126    174000.0
 Name: SalePrice, Length: 1168, dtype: float64,
 892     154500.0
 1105    325000.0
 413     115000.0
 522     159000.0
 1036    315500.0
           ...
 479      89471.0
 1361    260000.0
 802     189000.0
 651     108000.0
 722     124500.0
 Name: SalePrice, Length: 292, dtype: float64)

In [83]:
model4.fit(X_train2, y_train2)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [84]:
y_pred2 = model4.predict(X_test2)

In [85]:
r2 = r2_score(y_test2, y_pred2)

In [86]:
# after using xgboost and data transformation 0.417 to 0.817
r2

0.817233983730327

In [87]:
# model 5 - xgboost with shifted parameters
model5 = XGBRegressor(n_estimators=300, learning_rate=0.03, max_depth=5, subsample=0.8, colsample_bytree=0.8, random_state=42)

In [88]:
model5.fit(X_train2, y_train2)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [89]:
y_pred3 = model5.predict(X_test2)

In [90]:
r2_second = r2_score(y_test2, y_pred3)

In [91]:
# not much change therefore stable model
r2_second

0.8166393767253524

In [92]:
# final predicitons
final_predictions = model5.predict(X_test2)

In [93]:
test_ids = X_test2.index
submission = pd.DataFrame({'Id':test_ids, 'Actual_Price':y_test2,'SalePrice':final_predictions})

In [98]:
submission.to_csv('final_house_predictions.csv', index=False)

In [99]:
submission

        Id  Actual_Price      SalePrice
892    892      154500.0  151907.125000
1105  1105      325000.0  285269.062500
413    413      115000.0  106592.117188
522    522      159000.0  127544.742188
1036  1036      315500.0  258528.750000
...    ...           ...            ...
479    479       89471.0  127793.671875
1361  1361      260000.0  224764.515625
802    802      189000.0  164961.375000
651    651      108000.0  143769.171875
722    722      124500.0  129508.203125

[292 rows x 3 columns]

In [100]:
mae = mean_absolute_error(y_pred2, y_test2)
rmse = root_mean_squared_error(y_pred2, y_test2)

In [101]:
mae, rmse

(23764.94404163099, 37441.62074986153)